import React, { Component } from 'react';
import Link from 'next/link';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

class ServiceDetails extends Component {

    render() {

        return (
            <section className="service-detals pt-0 pb-100 fix">
                <div className="container">
                    <div className="row">
                        <div className="col-xxl-8 col-xl-8 col-lg-8">
                            <div className="develop-wrapper">
                                <div className="develop-thumb">
                                    <img src="assets/img/service/service-img-5.jpg" alt=""/>
                                </div>
                                <div className="develop-content">
                                    <h3 className="service-title">REACTIVE AND NON-REACTIVE MATRIX STIMULATIONS.</h3>
                                    <h4>Thermochemical Combined and Controlled System STCC ™. </h4>
                                    <p> EIt is a thermochemical matrix stimulation system able to reach high temperatures and pressures. </p>
                                </div>
                            </div>

                            <div className="planning-wrapper pt-50">
                                <div className="row">
                                    <div className="col-xxl-6 col-xl-6 col-lg-6">
                                        <div className="plan-thumb mb-md-40 mb-xs-40">
                                            <img src="assets/img/service/service-img-6.png" alt=""/>
                                        </div>
                                    </div>
                                    <div className="col-xxl-6 col-xl-6 col-lg-6">
                                        <div className="plan-content">
                                            <h4>Results generated by the STCC™</h4>

                                            <ul>
                                                <li><i><FontAwesomeIcon icon={['fas', 'check']} /></i>- Generates an increase in temperature, thus allowing the removal of organic deposits such as Asphaltenes and Paraffins.</li>
                                                <li><i><FontAwesomeIcon icon={['fas', 'check']} /></i>Brine obtained is not harmful to the formation. Inhibits the swelling of the clays in formation.</li>
                                                <li><i><FontAwesomeIcon icon={['fas', 'check']} /></i>Nitrogen generation (N2), pressure relief in the hydrostatic column increases mobility of crude oil in the pipeline.</li>
                                            </ul>
                                        </div>
                                    </div>

                                    <div className="col-xxl-12">
                                        <div className="plan-content pr-10 pt-50 pt-xs-30 pt-md-30 pb-15">

                                        </div>
                                    </div>

                                </div>
                            </div>


                        </div>
                        <div className="col-xxl-4 col-xl-4 col-lg-4">
                            <div className="sidebar-wrap">
                                <div className="widget_categories grey-bg">
                                    <h4 className="bs-widget-title pl-20">Benefits</h4>
                                    <ul>
                                        <li><Link href="/service-details"><a>Easy application. <i><FontAwesomeIcon icon={['fas', 'long-arrow-alt-right']} /></i></a></Link></li>
                                        <li><Link href="/service-details"><a> Controlled and instantaneous reaction.<i><FontAwesomeIcon icon={['fas', 'long-arrow-alt-right']} /></i></a></Link></li>
                                        <li><Link href="/service-details"><a>Recovery of the deferred production rate.<i><FontAwesomeIcon icon={['fas', 'long-arrow-alt-right']} /></i></a></Link></li>
                                        <li><Link href="/service-details"><a> Facilitates the work in series of wells.<i><FontAwesomeIcon icon={['fas', 'long-arrow-alt-right']} /></i></a></Link></li>
                                        <li><Link href="/service-details"><a> Fluid mobility improvement in wells. <i><FontAwesomeIcon icon={['fas', 'long-arrow-alt-right']} /></i></a></Link></li>
                                    </ul>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div className="container">
                    <div className="row">
                        <div className="col-xxl-8 col-xl-8 col-lg-8">
                            <div className="develop-wrapper">
                                <div className="develop-thumb">
                                <div className="develop-content">

                                    <h4>Thermochemical Fracturing System SFT ™. </h4>
                                    <p> Fracturing of unconventional reservoirs as a consequence of the expansion of
                                    Nitrogen (N2) generated during the exothermic reaction of the technology.</p>
                                </div>
                                    <img src="assets/img/service/Sftbanner (1).png" alt=""/>
                                </div>

                            </div>

                            <div className="planning-wrapper pt-50">
                                <div className="row">
                                    <div className="col-xxl-6 col-xl-6 col-lg-6">
                                        <div className="plan-thumb mb-md-40 mb-xs-40">
                                            <img src="assets/img/service/Imagen1sgft.png" alt=""/>
                                        </div>
                                    </div>
                                    <div className="col-xxl-6 col-xl-6 col-lg-6">
                                        <div className="plan-content">
                                            <h4>Efectos generados por el SFT™</h4>

                                            <ul>
                                                <li><i><FontAwesomeIcon icon={['fas', 'check']} /></i>Based on the pressure estimates produced by the reaction,
                                                Castillomax proposes the development of its application in
                                                unconventional deposits (shale gas / shale oil) as an alternative to
                                                conventional hydraulic fracturing</li>
                                                <li><i><FontAwesomeIcon icon={['fas', 'check']} /></i>Increased permeability due to fractures.</li>
                                                <li><i><FontAwesomeIcon icon={['fas', 'check']} /></i>The reaction reaches about 220 ºF.</li>
                                                  <li><i><FontAwesomeIcon icon={['fas', 'check']} /></i>It allows the control of the pressure generated at the bottom.</li>
                                            </ul>
                                        </div>
                                    </div>

                                    <div className="col-xxl-12">
                                        <div className="plan-content pr-10 pt-50 pt-xs-30 pt-md-30 pb-15">

                                        </div>
                                    </div>

                                </div>
                            </div>
                                    <div className="col-xxl-12">
                                        <div className="plan-content pr-10 pt-50 pt-xs-30 pt-md-30 pb-15">

                                        </div>
                                    </div>

                        </div>
                        <div className="col-xxl-4 col-xl-4 col-lg-4">
                            <div className="sidebar-wrap">
                                <div className="widget_categories grey-bg">
                                    <h4 className="bs-widget-title pl-20">Benefits</h4>
                                    <ul>
                                        <li><Link href="/service-details"><a> Generation of high levels of pressure.<i><FontAwesomeIcon icon={['fas', 'long-arrow-alt-right']} /></i></a></Link></li>
                                        <li><Link href="/service-details"><a> Reduction of fresh water consumption compared to Hydraulic Fracturing<i><FontAwesomeIcon icon={['fas', 'long-arrow-alt-right']} /></i></a></Link></li>
                                        <li><Link href="/service-details"><a> Adaptability to surface equipment.<i><FontAwesomeIcon icon={['fas', 'long-arrow-alt-right']} /></i></a></Link></li>
                                        <li><Link href="/service-details"><a>Effectiveness in the generation of fractures.<i><FontAwesomeIcon icon={['fas', 'long-arrow-alt-right']} /></i></a></Link></li>


                                    </ul>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </section>
        );
    }
}

export default ServiceDetails;
